symbol = {
    "para": "[\(\)]",
    "space": " ",
    "quote": "\"",
    "colon": "\:",
    "comma": "\,",
    "underscore": "_",
    "tag": "[<>]",
    "dot": "\.",
    "equals": "=",
    "equal": "=",
    "square": "[\[\]]",
}

alphabet = {
    "alpha": "[aA]",
    "bravo": "[bB]",
    "charlie": "[cC]",
    "delta": "[dD]",
    "echo": "[eE]",
    "foxtrot": "[fF]",
    "golf": "[gG]",
    "hotel": "[hH]",
    "india": "[iI]",
    "juliet": "[jJ]",
    "kilo": "[kK]",
    "lima": "[lL]",
    "mike": "[mM]",
    "november": "[nN]",
    "oscar": "[oO]",
    "papa": "[pP]",
    "quebec": "[qQ]",
    "romeo": "[rR]",
    "sierra": "[sS]",
    "tango": "[tT]",
    "uniform": "[uU]",
    "victor": "[vV]",
    "whiskey": "[wW]",
    "x-ray": "[xX]",
    "yankee": "[yY]",
    "zulu": "[zZ]",
}

tokens = dict(symbol.items() + alphabet.items())